import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	htmap: [{type: 'autogenerated', dirName: 'htmap'}],
	nukkit: [{type: 'autogenerated', dirName: 'nukkit'}],
	dragonfly: [{type: 'autogenerated', dirName: 'dragonfly'}],
	php: [{type: 'autogenerated', dirName: 'php'}],
	python: [{type: 'autogenerated', dirName: 'python'}],
	linux: [{type: 'autogenerated', dirName: 'linux'}],
};

export default sidebars;