import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	php: [{type: 'autogenerated', dirName: 'php'}],
	python: [{type: 'autogenerated', dirName: 'python'}],
	linux: [{type: 'autogenerated', dirName: 'linux'}],
	java: [{type: 'autogenerated', dirName: 'java'}],
	'ethical-hacking': [{type: 'autogenerated', dirName: 'ethical-hacking'}],
	cybersecurity: [{type: 'autogenerated', dirName: 'cybersecurity'}],
	'pocketmine-mp': [{type: 'autogenerated', dirName: 'pocketmine-mp'}],
	nukkit: [{type: 'autogenerated', dirName: 'nukkit'}],
	dragonfly: [{type: 'autogenerated', dirName: 'dragonfly'}],
};

export default sidebars;